"""initial_19_tables

Revision ID: a2140a39f67d
Revises: 
Create Date: 2026-09-01 22:38:45.167757
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a2140a39f67d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###